trigger: none

pool : omkarwipropool

stages:
  - stage : deployment
    displayName: deploymentnode
    jobs:
      - job : deploymentjob
        steps:
        - task: NodeTool@0
          inputs:
            versionSource: 'spec'
            versionSpec: '16.x'

        - task: Npm@1
          inputs:
            command: 'install'
            workingDir: '$(System.DefaultWorkingDirectory)'


        - task: Npm@1
          inputs:
            command: 'custom'
            workingDir: '$(System.DefaultWorkingDirectory)'
            customCommand: 'run build'


        - task: ArchiveFiles@2
          inputs:
            rootFolderOrFile: '$(System.DefaultWorkingDirectory)/build'
            includeRootFolder: false
            archiveType: 'zip'
            archiveFile: '$(Build.ArtifactStagingDirectory)/build.zip'
            replaceExistingArchive: true

        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'told-artifacts'
            publishLocation: 'Container'